name: CI

on: [push, pull_request]

jobs:
  
  build_yarg_updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_wii" -type f -delete
      - name: Clean up files
        run: |
           rm _ark/songs/missing_song_data.dta
           rm _ark/songs/missing_song_data_updates.dta
           rm  -rf _ark/songs/dta_sections
           rm  -rf _ark/songs/dta_collection
           mv _ark/songs/beencaughtstealing _ark/songs/updates/beencaughtstealing
           mv _ark/songs/getupstandup _ark/songs/updates/getupstandup
           mv _ark/songs/nooneknows _ark/songs/updates/nooneknows
           mv _ark/songs/radarlove _ark/songs/updates/radarlove
           mv _ark/songs/thepoweroflove _ark/songs/updates/thepoweroflove
           mv _ark/songs/updates _ark/songs/songs_updates
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-YARG-Updates
          path: _ark/songs

  build_wii:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Download gen
        run: |
          pip install gdown
          cd _build/wii/wit_input/files/
          gdown --folder 1_oDRcx1IUzvPWrOAF_S4nlCwnHtLdb5S
          cd /home/runner/work/rock-band-3-deluxe/rock-band-3-deluxe/
          mkdir ./_build/wii/RB3DX
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod a+x dependencies/linux/arkhelper
          chmod a+x dependencies/linux/dtab
          chmod a+x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove other console files
        run: |
          find . -name "*.*_ps3" -type f -delete
          find . -name "*.*_xbox" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: sudo dependencies/linux/arkhelper patchcreator ./_build/wii/wit_input/files/gen/main_wii.hdr -a ./_ark -o ./_build/wii/wit_input/files
        continue-on-error: true
      - name: remove stuff
        run: |
          rm ./_build/wii/wit_input/files/gen/main_wii_9.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_8.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_7.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_6.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_5.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_4.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_3.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_2.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_1.ark
          rm ./_build/wii/wit_input/files/gen/main_wii_0.ark
          mv ./_build/wii/wit_input/files/gen/main_wii_10.ark ./_build/wii/RB3DX/gen/main_wii_10.ark
          mv ./_build/wii/wit_input/files/gen/main_wii.hdr ./_build/wii/RB3DX/gen/main_wii.hdr
          mkdir ./_build/wii/Riivolution
          cp ./_build/wii/Riivolution/RB3DX.xml ./_build/wii/Riivolution/RB3DX.xml
          mkdir ./_build/wii/Riivolution/config
          cp ./_build/wii/Riivolution/config/SZBE.xml ./_build/wii/Riivolution/config/SZBE.xml
          rm -rf ./_build/wii/wit_input
          rm -rf ./_build/wii/Riivolution
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Wii
          path: ./_build/wii

  build_xbox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          chmod +x dependencies/linux/arkhelper
          chmod +x dependencies/linux/dtab
          chmod +x dependencies/linux/superfreq
          pip install gitpython
          pip install mido
      - name: Remove PS3 files
        run: |
          find . -name "*.*_ps3" -type f -delete
      - name: Print build info
        run: |
          echo $GITHUB_SHA_SHORT
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/linux/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      - name: Remove Excess files
        run: |
          find . -name "*.txt" -type f -delete
          find . -name "*.zbm" -type f -delete
      
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-Xbox
          path: _build/xbox

  build_ps3:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Download Mackiloha
        run: |
          pip install requests
          python dependencies/dev_scripts/download_mackiloha.py
      - name: Set env
        run: |
          pip install gitpython
          pip install mido
          pip install requests
      - name: fetch TrueAncestor PKG Repacker
        run: |
          python dependencies/dev_scripts/download_ta_pkg_repacker.py
      - name: Remove Xbox files
        run: |
          Get-ChildItem _ark/ -recurse -include *.*_xbox | remove-item
          Get-ChildItem _ark/ -recurse -include *.*_wii | remove-item
      - name: Print build info
        run: |
          $GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)".ToUpper()
          python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
      - name: Build ARK
        run: |
          dependencies/windows/arkhelper.exe dir2ark _ark _build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      - name: Build PKG
        run: |
          $sha_short="$(git rev-parse --short HEAD)".ToUpper()
          $content="UP8802-BLUS30463_00-RB3DXNITE"
          $packageversion="1.05"
          dependencies/ta_pkg_repacker_tools/make_package_npdrm_retail.exe --k-licensee 0x00000000000000000000000000000000 --drm-type Local --package-version $packageversion --content-type GameData --content-id ($content + $sha_short) dependencies/ta_pkg_repacker_tools/package.conf _build/ps3

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: RB3DX-PS3
          path: '*.pkg'